### ISSUE TITLE
first commit

### ISSUE THREAD

**Issue by MCON** [ReekenX/phpcheck-git#8]
I've noticed that your hook allows to pass the very first commit with a mistake.
If i init a git repository, add your pre-commit hook there. Then i create a file with a syntax error and commit it then it will be passed into repository. However if i already have some commits then it won't be passed. 

Also i want to note that your script is a shell script (almost). You shuld add
#!/bin/sh
but not
#!/bin/bash
All servers have shell but not all of them have bash

**Comment by ReekenX** [comment]
Thanks for bug report.

Issue with Initial commit syntax checking was fixed in 6e15f548ef559846735d6a70b5906d08151b7f82.

Good idea to keep in mind for shell. Too bad, but I was not able to do fast-fix for shell changing due to current implementation. PR's are always welcome :)

**Comment by MCON** [comment]
Well before you last commit it worked with
#!/bin/sh
on my company server now it does not
(we don't have bash)
